name: Flutter CI Pipeline

env:
  FLUTTER_VERSION: '3.29.2'

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging, main ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release'
        required: false
        default: false
        type: boolean
      version:
        description: 'Version number (e.g., X.Y.Z)'
        required: false
        type: string

jobs:
  format:
    name: Format Check
    uses: ./.github/workflows/job-format.yml
    with:
      flutter_version: ${{ env.FLUTTER_VERSION }}

  test_macos:
    name: Run Tests (macOS)
    needs: format
    uses: ./.github/workflows/job-test-macOS.yml
    with:
      flutter_version: ${{ env.FLUTTER_VERSION }}

  test_windows:
    name: Run Tests (Windows)
    needs: format
    uses: ./.github/workflows/job-test-windows.yml
    with:
      flutter_version: ${{ env.FLUTTER_VERSION }}

  build_ios:
    name: Build iOS App
    needs: [format, test_macos, test_windows]
    uses: ./.github/workflows/job-build-ios.yml
    with:
      flutter_version: ${{ env.FLUTTER_VERSION }}
      build_number: ${{ github.run_number }}
    secrets: inherit

  build_android:
    name: Build Android App
    needs: [format, test_macos, test_windows]
    uses: ./.github/workflows/job-build-android.yml
    with:
      flutter_version: ${{ env.FLUTTER_VERSION }}
      build_number: ${{ github.run_number }}
    secrets: inherit

  release:
    name: Package and Release
    needs: [format, test_macos, test_windows, build_ios, build_android]
    if: |
      success() && (
        (github.event_name == 'workflow_dispatch' && 
        inputs.create_release == true) &&
        github.ref == 'refs/heads/main'
      )
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation
      
      - name: Download iOS build
        uses: actions/download-artifact@v4
        with:
          name: unsigned-ipa
          path: artifacts/ios/ipa
        continue-on-error: true # Au cas où l'artifact n'existe pas
      
      - name: Download iOS XCArchive
        uses: actions/download-artifact@v4
        with:
          name: xcarchive
          path: artifacts/ios/xcarchive
      
      - name: Download Android build
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: artifacts/android/apk
      
      - name: Download Android App Bundle
        uses: actions/download-artifact@v4
        with:
          name: release-aab
          path: artifacts/android/aab
      
      - name: Set version
        id: set_version
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          myToken: ${{ github.token }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          tag_name: v${{ steps.set_version.outputs.version }}
          name: Release v${{ steps.set_version.outputs.version }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.changelog }}
          files: |
            artifacts/ios/ipa/*.ipa
            artifacts/android/apk/*.apk
            artifacts/android/aab/*.aab
      
      - name: Release status
        if: steps.create_release.outcome == 'success'
        run: echo "Release created successfully! 🚀"