name: Build for iOS

on:
  workflow_call:
    inputs:
      flutter_version:
        required: false
        type: string
        default: '3.29.2'
      build_number:
        required: false
        type: string
        default: ${{ github.run_number }}
    outputs:
      ipa_path:
        description: "Path to generated IPA file"
        value: ${{ jobs.build_ios.outputs.ipa_path }}
      xcarchive_path:
        description: "Path to generated XCArchive file"
        value: ${{ jobs.build_ios.outputs.xcarchive_path }}

jobs:
  build_ios:
    name: Build iOS Artifacts
    runs-on: macos-latest
    outputs:
      ipa_path: ${{ steps.build_artifacts.outputs.ipa_path }}
      xcarchive_path: ${{ steps.build_artifacts.outputs.xcarchive_path }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: 'stable'
          cache: true
      
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Patch Podfile to include PhoneNumberKit
        run: |
          echo "Patching Podfile to add PhoneNumberKit"
          echo "  pod 'PhoneNumberKit', '~> 3.3'" >> ios/Podfile

      - name: Build iOS artifacts
        id: build_artifacts
        run: |
          # Create directory for build output
          mkdir -p build/ios/outputs
          
          # Generate build for XCArchive
          flutter build ios --release --no-codesign --build-number=${{ inputs.build_number }}
          
          # Save the archive path
          ARCHIVE_PATH=build/ios/archive/Runner.xcarchive
          
          # Create archive directory
          mkdir -p build/ios/archive
          
          # Build archive with xcodebuild
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -derivedDataPath ../build/ios/archive DEVELOPMENT_TEAM="" CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO
          cd ..
          
          # Create a plain IPA (this is just for CI purposes - not a validly signed IPA)
          # This step creates a basic IPA structure from the app binary
          mkdir -p build/ios/outputs/Payload
          cp -r build/ios/archive/Build/Products/Release-iphoneos/Runner.app build/ios/outputs/Payload/
          cd build/ios/outputs
          zip -r app-unsigned.ipa Payload
          cd ../../..
          
          # Set output variables
          echo "ipa_path=build/ios/outputs/app-unsigned.ipa" >> $GITHUB_OUTPUT
          echo "xcarchive_path=build/ios/archive/Build/Products/Release-iphoneos" >> $GITHUB_OUTPUT
      
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/outputs/app-unsigned.ipa
          retention-days: 7
      
      - name: Upload XCArchive artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcarchive
          path: build/ios/archive/Build/Products/Release-iphoneos
          retention-days: 7